const mongoose = require('mongoose');
const { Student, calculateGPA } = require('../models/Student');
require('dotenv').config();

const sampleStudentData = [
  {
    "registrationNo": "419217687",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "RX", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "B-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "B+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "-", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "B+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "-", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "B-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "A-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "C", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "319217690",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "A+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "A+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "RX", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "C+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "C+", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "620211234",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "C+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "A-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "B+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "C+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "C+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "B-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "B-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "C+", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "520131554",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "A+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "C+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "C+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "C+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "B-", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "A-", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "A", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "417661546",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "C+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "B-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "-", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "B+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "C+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "-", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "B-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "A-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "C", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "416988177",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "RX", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "B-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "B+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "A-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "A", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "419217699",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "RX", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "B-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "C+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "C+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "C+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "C", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "C", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "C", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "112001887",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "RX", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "A-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "A", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "A", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "A", level: 5, credits: 3, isCompulsory: true }
    ]
  },

  {
    "registrationNo": "419217696",
    "courses": [
      { courseCode: "AGM3203", courseName: "Communication Skills", grade: "A-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "AGM4307", courseName: "Economics and Marketing for Engineers", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "CVM5401", courseName: "Accounting for Engineers", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "DMM6601", courseName: "Management for Engineers", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "DMX3107", courseName: "Workshop Practice", grade: "B+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3305", courseName: "Introduction to Engineering Design Graphics", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "DMX3401", courseName: "Fluid Mechanics & Thermodynamics", grade: "C", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEM6201", courseName: "Professional Practice", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEW4301", courseName: "Industrial Training (Electronics)", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEW5501", courseName: "Industrial Training (Computer)", grade: "RX", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX3262", courseName: "Introduction to Object Oriented Programming", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3331", courseName: "Electrical Measurements and Instrumentation", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3336", courseName: "Communications and Computer Technology", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3351", courseName: "Electronics I", grade: "B", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3372", courseName: "Programming in Python", grade: "C+", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3410", courseName: "Introduction to Electrical Engineering", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX3417", courseName: "Software Development for Engineers", grade: "B-", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "A", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4332", courseName: "Electrical Power", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4347", courseName: "Software Engineering Concepts", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4351", courseName: "Electronics II", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4435", courseName: "Data Structures and Algorithms", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX4436", courseName: "Microprocessors and Interfacing", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5270", courseName: "Information Security", grade: "B", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5346", courseName: "Embedded Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5351", courseName: "Digital Electronic Systems", grade: "B+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5360", courseName: "Signals and Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5434", courseName: "Data Communications and Networking", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5467", courseName: "Software Testing and Quality Assuarance", grade: "A+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6181", courseName: "Research Methodology and Project Identification (Computer Engineering)", grade: "C", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX6335", courseName: "Compiler Design", grade: "B", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7241", courseName: "Neural Network & Fuzzy Logic Applications", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "B", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7337", courseName: "System Design in Groups", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7340", courseName: "AI Techniques & Agent Technology", grade: "C+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEX7436", courseName: "Processor Design", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "EEY4181", courseName: "Group project (Computer)", grade: "A+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEY7881", courseName: "Engineering Research Project (Computer Engineering)", grade: "C", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "LLJ3245", courseName: "Introduction to laws of Sri Lanka", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHJ4241", courseName: "History of Technology", grade: "C+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHJ5342", courseName: "Technology, society and environmenty", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ3551", courseName: "Engineering Mathematics I", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ3552", courseName: "Engineering Mathematics II", grade: "A", level: 3, credits: 3, isCompulsory: false },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "C-", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "C+", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5554", courseName: "Engineering Mathematics IV", grade: "C", level: 5, credits: 3, isCompulsory: true }
    ]
  },
  {
    registrationNo: "419217688",
    courses: [
      { courseCode: "EEX4331", courseName: "Circuit Theory and Design", grade: "B+", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "EEX5335", courseName: "Operating Systems", grade: "A", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX5536", courseName: "Computer architecture", grade: "A-", level: 5, credits: 3, isCompulsory: true },
      { courseCode: "EEX6236", courseName: "Advanced Computer Architecture", grade: "B+", level: 6, credits: 3, isCompulsory: true },
      { courseCode: "EEX7244", courseName: "Data Mining", grade: "A+", level: 7, credits: 3, isCompulsory: true },
      { courseCode: "MHZ4553", courseName: "Engineering Mathematics III", grade: "B", level: 4, credits: 3, isCompulsory: true },
      { courseCode: "MHZ5355", courseName: "Discrete Mathematics", grade: "A-", level: 5, credits: 3, isCompulsory: true }
    ]
  }

];


async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb+srv://kasunibandara97:MLGowj6CUu8whH9s@cluster0.fbhvj.mongodb.net/university_gpa'); 
    console.log('Connected to MongoDB');
    
    // Clear existing data
    await Student.deleteMany({});
    console.log('Cleared existing student data');
    
    // Insert sample data with calculated GPA
    for (let studentData of sampleStudentData) {
      const gpa = calculateGPA(studentData.courses);
      const student = new Student({
        ...studentData,
        gpa: gpa
      });
      await student.save();
      console.log(`Inserted student ${studentData.registrationNo} with GPA: ${gpa}`);
    }
    
    console.log('Database seeded successfully');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();